services:
  redis:
    image: redis:7.2.1
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}

  api:
    build:
      context: .
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
